---
env:
  node: true
  jest/globals: true

parser: babel-eslint

extends:
  - airbnb-base
  - '@acme'
  - 'plugin:jest/recommended'
  - 'plugin:jest/style'

plugins:
  - jest

rules:
  filenames/match-regex: off

overrides:
  - files:
      - 'libdefs/**/*.js'
    rules:
      no-use-before-define: off
      flowtype/no-types-missing-file-annotation: off
  - files:
      - 'scripts/**/*.js'
    rules:
      '@acme/require-variable-type': off
    settings:
      flowtype:
        onlyFilesWithFlowAnnotation: true
